"""
Configuration for GitHub Integration and Pull Request Creation
Repository: https://github.com/RajBhattacharyya/pv_app_api
"""

import os
from pathlib import Path

# GitHub Configuration for Pull Request Creation
GITHUB_CONFIG = {
    "repository": {
        "owner": "RajBhattacharyya",
        "name": "pv_app_api",
        "url": "https://github.com/RajBhattacharyya/pv_app_api",
        "default_branch": "main",
        "language": "javascript",
        "framework": "node.js",
    },
    "pull_request": {
        "enabled": True,
        "base_branch": "main",
        "branch_prefix": "codeyogi/",
        "auto_merge": False,
        "labels": ["automated", "codeyogi", "optimization"],
        "reviewers": ["RajBhattacharyya"],
        "template": {
            "title_prefix": "[CodeYogi] ",
            "description_template": """
## 🤖 CodeYogi Automated Optimization

This pull request was automatically generated by CodeYogi's agentic AI system.

### 📋 Changes Made:
{changes_summary}

### 🎯 Optimization Type:
{optimization_type}

### ✨ Improvements:
{improvements_list}

### 🔍 Analysis Results:
{analysis_summary}

### 🧪 Testing:
- [ ] Automated tests pass
- [ ] Manual review completed
- [ ] Performance impact assessed

### 📊 Metrics:
- **Files Modified**: {files_modified}
- **Lines Changed**: {lines_changed}
- **Estimated Impact**: {impact_level}

---
*Generated by CodeYogi Agentic AI System* 🧘‍♂️
""",
        },
    },
    "workflow_optimization": {
        "enabled": True,
        "target_files": [
            ".github/workflows/ci.yml",
            ".github/workflows/cd.yml",
            ".github/workflows/node.js.yml",
        ],
        "optimizations": [
            "node_js_caching",
            "parallel_jobs",
            "security_scanning",
            "dependency_updates",
            "docker_optimization",
        ],
    },
    "code_analysis": {
        "enabled": True,
        "scan_paths": ["app.js", "routes/", "controllers/", "models/", "package.json"],
        "exclude_paths": ["node_modules/", ".git/", "coverage/", "dist/"],
    },
}

# Environment Configuration Template
ENV_TEMPLATE = """
# CodeYogi Configuration for Pull Request Creation
# Add these to your environment variables or .env file

# GitHub Personal Access Token (required for PR creation)
# Generate at: https://github.com/settings/tokens
# Required scopes: repo, pull_requests, contents, metadata
GITHUB_TOKEN=your_github_personal_access_token_here

# Groq API Key (optional, for AI-enhanced optimization)
# Get from: https://console.groq.com/
GROQ_API_KEY=your_groq_api_key_here

# Gemini API Key (optional, for SEO optimization)
# Get from: https://makersuite.google.com/app/apikey
GEMINI_API_KEY=your_gemini_api_key_here

# Repository Configuration
TARGET_REPO_OWNER=RajBhattacharyya
TARGET_REPO_NAME=pv_app_api
TARGET_REPO_URL=https://github.com/RajBhattacharyya/pv_app_api

# Pull Request Settings
PR_ENABLED=true
PR_AUTO_MERGE=false
PR_BASE_BRANCH=main
PR_BRANCH_PREFIX=codeyogi/
"""


def create_env_file():
    """Create a .env template file"""
    env_path = Path(".env.template")
    with open(env_path, "w") as f:
        f.write(ENV_TEMPLATE)
    print(f"✅ Created {env_path} - Copy to .env and fill in your tokens")


def generate_github_workflow():
    """Generate an optimized GitHub workflow for the Node.js project"""
    workflow_content = """name: Node.js CI/CD with CodeYogi Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'
  CACHE_VERSION: v1

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16, 18, 20]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ env.CACHE_VERSION }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-${{ env.CACHE_VERSION }}-
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint --if-present
    
    - name: Run tests
      run: npm test --if-present
    
    - name: Run security audit
      run: npm audit --audit-level high
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      if: matrix.node-version == 18
      with:
        file: ./coverage/lcov.info

  build:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build --if-present
    
    - name: Build Docker image
      run: docker build -t pv-app-api:${{ github.sha }} .
    
    - name: Test Docker image
      run: |
        docker run -d --name test-container -p 3000:3000 pv-app-api:${{ github.sha }}
        sleep 10
        curl -f http://localhost:3000/health || exit 1
        docker stop test-container

  security:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [test, build, security]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Deploy to staging
      run: |
        echo "Deploying to staging environment..."
        # Add your deployment commands here
    
    - name: Notify CodeYogi
      run: |
        curl -X POST "http://your-codeyogi-instance/webhooks/github" \\
          -H "Content-Type: application/json" \\
          -H "X-GitHub-Event: deployment" \\
          -d '{
            "action": "completed",
            "deployment": {
              "environment": "staging",
              "ref": "${{ github.sha }}"
            },
            "repository": {
              "name": "pv_app_api",
              "full_name": "RajBhattacharyya/pv_app_api"
            }
          }'
"""

    workflow_path = Path(".github/workflows/codeyogi-optimized.yml")
    workflow_path.parent.mkdir(parents=True, exist_ok=True)
    with open(workflow_path, "w") as f:
        f.write(workflow_content)
    print(f"✅ Created optimized workflow: {workflow_path}")


def setup_webhook_instructions():
    """Provide instructions for setting up GitHub webhooks"""
    instructions = """
🔗 GitHub Webhook Setup Instructions

To enable automatic pull request creation and repository monitoring:

1. 📍 Go to your repository settings:
   https://github.com/RajBhattacharyya/pv_app_api/settings/hooks

2. 🆕 Click "Add webhook"

3. ⚙️ Configure the webhook:
   - Payload URL: http://your-codeyogi-server:8000/webhooks/github
   - Content type: application/json
   - Secret: (optional, but recommended)
   
4. 📋 Select events to trigger:
   ✅ Push events
   ✅ Pull request events  
   ✅ Issue events
   ✅ Deployment events
   ✅ Repository events

5. ✅ Click "Add webhook"

6. 🧪 Test the webhook:
   - Make a commit to your repository
   - Check CodeYogi logs for webhook processing
   - Verify agent execution in event history

🔑 Required Permissions for GitHub Token:
   - repo (full repository access)
   - pull_requests (create and modify PRs)
   - contents (read and write repository contents)
   - metadata (read repository metadata)
   - actions (if using GitHub Actions integration)

🚀 Once configured, CodeYogi will automatically:
   - Monitor code changes
   - Analyze repository structure
   - Optimize workflows
   - Create pull requests with improvements
   - Deploy applications using best practices
"""
    print(instructions)


def main():
    """Setup GitHub integration for pull request creation"""
    print("🔧 Setting up GitHub Integration for Pull Request Creation")
    print("=" * 70)

    print("\n1. 📝 Creating configuration files...")
    create_env_file()

    print("\n2. ⚙️ Generating optimized GitHub workflow...")
    generate_github_workflow()

    print("\n3. 📋 Repository configuration:")
    print(f"   Repository: {GITHUB_CONFIG['repository']['url']}")
    print(f"   Language: {GITHUB_CONFIG['repository']['language']}")
    print(f"   Framework: {GITHUB_CONFIG['repository']['framework']}")
    print(f"   PR Enabled: {GITHUB_CONFIG['pull_request']['enabled']}")

    print("\n4. 🔗 Webhook setup instructions:")
    setup_webhook_instructions()

    print("\n✅ Setup complete! Next steps:")
    print("   1. Copy .env.template to .env and add your GitHub token")
    print("   2. Commit the new workflow file to your repository")
    print("   3. Set up the GitHub webhook as instructed above")
    print("   4. Test the integration with a code push")

    print(f"\n🎉 CodeYogi is ready to create pull requests for:")
    print(f"   {GITHUB_CONFIG['repository']['url']}")


if __name__ == "__main__":
    main()
